apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 550992133034.dkr.ecr.ap-south-1.amazonaws.com/k8s-app:latest
        ports:
        - containerPort: 80
