apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-redis
  template:
    metadata:
      labels:
        app: test-redis
    spec:
      containers:
      - name: redis
        image: 550992133034.dkr.ecr.ap-south-1.amazonaws.com/k8s-app:latest
        ports:
        - containerPort: 8001
